"""Internal messaging domain: canonical models, bridges, routing, and ingestion.

Protocol-specific behavior lives in ``bridge/<name>`` packages that register themselves with the
facade. Application code uses only this package's canonical models and unified API.
"""

# Canonical model, interface, facade, and signals.
from .models import (
    CONVERSATION_OUTPUT_PENDING_METADATA_KEY,
    CONVERSATION_ROUND_METADATA_KEY,
    TASK_REQUESTED_METADATA_KEY,
    DISPLAYED_DOCUMENT_METADATA_KEY,
    TASK_REASONING_EFFORT_METADATA_KEY,
    Capability,
    ListenerState,
    File,
    Attachment,
    Message,
    Room,
    RoomUser,
    MessengerUser,
    Interaction,
    ConversationType,
    kind_from_mime,
)
from .interface import HistoryPage, BridgeSpec, ParamDef, NotSupported
from .events import Signal, message_journaled, message_received, message_sent, interaction_changed, message_admitting
from .native_interactions import read_internal_interaction, answer_internal_interaction
from .inbound import on_message, dispatch_incoming
from .facade import (
    MessengerFacade,
    register_bridge,
    set_resolver,
    get_messenger,
    get_messenger_for,
    get_default_messenger,
    get_factory,
    get_spec,
    all_specs,
    available_bridges,
    enabled_specs,
    registered_kinds,
    enabled_kinds,
    is_kind_enabled,
    kind_for_tool,
    normalize_kind,
)

# Lazy attachment ingestion.
from .ingest import (
    as_openai_content,
    as_prompt_block,
    describe,
    extract_text,
    fetch_bytes,
    image_parts,
)

# Application subscriber, resolver, and listener lifecycle.
from .service import (
    AppMessengerResolver,
    admit_incoming,
    handle_incoming,
    resolve_task_messaging,
    send_task_progress,
    messenger_for_agent,
    messenger_for_agent_connection,
    messenger_for_agent_tool_code,
    messenger_for_agent_kind,
    messenger_room_locator_known,
    start_listeners,
    stop_listeners,
    listeners_running,
    register_messaging,
    check_configuration,
    messaging_tool_records,
    search_agent_users,
)
from .reply_guard import (
    clear_room,
    note_reply,
    replied_recently,
    text_already_sent,
)
from .interactions import (
    ChoiceOption,
    PendingChoice,
    ChoiceRequest,
    ChoiceResolution,
    create_choice,
    list_pending_choices,
    register_choice_handler,
    resolve_pending_choice,
    resolve_from_message,
)
from .session import ConversationSessionSnapshot, build_conversation_session
from .voice_journal import (
    AudioRoomSpeakers,
    AudioSpeakerIdentity,
    get_audio_room_speakers,
    open_audio_room,
    record_audio_message,
)
from .configuration import (
    ResolvedMessengerConfiguration,
    resolve_messenger_configuration,
)
from .journal import hydrate_messages
from .resource_reference import attachment_resource_uri
from .contact_memory import observe_contact
from .contracts import (
    NativeMessengerInteraction,
    ChatViewerAgent,
    MessageResourcePreview,
    NativeMessengerAgent,
    NativeMessengerConnection,
    NativeMessengerFile,
    NativeMessengerFileAccess,
    NativeMessengerIdentityMapping,
    NativeMessengerMember,
    NativeMessengerMessage,
    NativeMessengerMessagePage,
    NativeMessengerRoom,
    NativeMessengerRoomPage,
    resolve_effective_topic_id,
)
from .link_preview import (
    extract_preview_references,
    materialize_preview_resource,
    PreviewResourceFile,
    preview_image,
    preview_reference,
    preview_references,
)
from .native_facade import (
    CHAT_TOOL_CODE,
    count_chat_unread,
    create_internal_room,
    clear_chat_identity_mapping,
    chat_file_access,
    fetch_chat_file_bytes,
    get_agent_chat_room,
    get_chat_message,
    get_chat_room,
    get_internal_room,
    human_external_id,
    has_chat_room_access,
    has_agent_chat_room_access,
    has_ai_chat_room_access,
    has_room_access,
    internal_agent_avatar,
    internal_connection,
    internal_direct_room_observation,
    internal_file_access,
    internal_file_for_connection,
    internal_history_observations,
    internal_outbound_observation,
    list_internal_agents,
    list_chat_identity_mappings,
    list_chat_message_agent_ids,
    list_chat_viewer_agents,
    list_chat_messages,
    list_chat_rooms,
    list_internal_messages,
    list_internal_rooms,
    mark_chat_room_read,
    mark_internal_room_read,
    set_internal_room_muted,
    set_chat_room_archived,
    set_chat_room_muted,
    update_chat_room_preferences,
    update_chat_room_topic,
    touch_chat_room,
    live_internal_file_ids,
    publish_internal_message,
    reassign_chat_message_topic,
    reconcile_internal_admissions,
    set_chat_identity_mapping,
    search_internal_users,
)

# Current conversation context used by room-explicit MCP tools.
from .mcp import (
    MessagingContext,
    current_context,
    set_context,
    reset_context,
)

__all__ = [
    "NativeMessengerInteraction",
    "read_internal_interaction",
    "answer_internal_interaction",
    "interaction_changed",
    # Canonical models.
    "CONVERSATION_OUTPUT_PENDING_METADATA_KEY",
    "CONVERSATION_ROUND_METADATA_KEY",
    "TASK_REQUESTED_METADATA_KEY",
    "DISPLAYED_DOCUMENT_METADATA_KEY",
    "TASK_REASONING_EFFORT_METADATA_KEY",
    "Capability",
    "ListenerState",
    "File",
    "Attachment",
    "Message",
    "Room",
    "RoomUser",
    "MessengerUser",
    "Interaction",
    "ConversationType",
    # Interface.
    "HistoryPage",
    "BridgeSpec",
    "ParamDef",
    "NotSupported",
    # Signals and inbound routing.
    "Signal",
    "message_journaled",
    "message_received",
    "message_admitting",
    "message_sent",
    "on_message",
    "dispatch_incoming",
    # Facade and registry.
    "register_bridge",
    "set_resolver",
    "get_messenger",
    "get_messenger_for",
    "get_default_messenger",
    "get_factory",
    "get_spec",
    "all_specs",
    "available_bridges",
    "enabled_specs",
    "registered_kinds",
    "enabled_kinds",
    "is_kind_enabled",
    "kind_for_tool",
    "normalize_kind",
    "MessengerFacade",
    # Attachment ingestion.
    "as_openai_content",
    "as_prompt_block",
    "describe",
    "extract_text",
    "fetch_bytes",
    "image_parts",
    # Application services.
    "AppMessengerResolver",
    "admit_incoming",
    "handle_incoming",
    "resolve_task_messaging",
    "send_task_progress",
    "messenger_for_agent",
    "messenger_for_agent_connection",
    "messenger_for_agent_tool_code",
    "messenger_for_agent_kind",
    "messenger_room_locator_known",
    "start_listeners",
    "stop_listeners",
    "listeners_running",
    "register_messaging",
    "check_configuration",
    "messaging_tool_records",
    "search_agent_users",
    "clear_room",
    "note_reply",
    "replied_recently",
    "text_already_sent",
    "ChoiceOption",
    "PendingChoice",
    "ChoiceRequest",
    "ChoiceResolution",
    "create_choice",
    "list_pending_choices",
    "register_choice_handler",
    "resolve_pending_choice",
    "resolve_from_message",
    "ConversationSessionSnapshot",
    "build_conversation_session",
    "AudioRoomSpeakers",
    "AudioSpeakerIdentity",
    "get_audio_room_speakers",
    "open_audio_room",
    "record_audio_message",
    "ResolvedMessengerConfiguration",
    "resolve_messenger_configuration",
    "hydrate_messages",
    "attachment_resource_uri",
    "observe_contact",
    "kind_from_mime",
    "CHAT_TOOL_CODE",
    "count_chat_unread",
    "NativeMessengerAgent",
    "ChatViewerAgent",
    "MessageResourcePreview",
    "NativeMessengerConnection",
    "NativeMessengerFile",
    "NativeMessengerFileAccess",
    "NativeMessengerIdentityMapping",
    "NativeMessengerMember",
    "NativeMessengerMessage",
    "NativeMessengerMessagePage",
    "NativeMessengerRoom",
    "NativeMessengerRoomPage",
    "resolve_effective_topic_id",
    "create_internal_room",
    "clear_chat_identity_mapping",
    "chat_file_access",
    "fetch_chat_file_bytes",
    "get_agent_chat_room",
    "get_chat_message",
    "get_chat_room",
    "get_internal_room",
    "human_external_id",
    "has_chat_room_access",
    "has_agent_chat_room_access",
    "has_ai_chat_room_access",
    "has_room_access",
    "internal_agent_avatar",
    "internal_connection",
    "internal_direct_room_observation",
    "internal_file_access",
    "internal_file_for_connection",
    "internal_history_observations",
    "internal_outbound_observation",
    "search_internal_users",
    "list_internal_agents",
    "list_chat_identity_mappings",
    "list_chat_message_agent_ids",
    "list_chat_viewer_agents",
    "list_chat_messages",
    "list_chat_rooms",
    "list_internal_messages",
    "list_internal_rooms",
    "mark_chat_room_read",
    "mark_internal_room_read",
    "set_internal_room_muted",
    "set_chat_room_archived",
    "set_chat_room_muted",
    "update_chat_room_preferences",
    "update_chat_room_topic",
    "touch_chat_room",
    "live_internal_file_ids",
    "publish_internal_message",
    "reassign_chat_message_topic",
    "reconcile_internal_admissions",
    "set_chat_identity_mapping",
    "extract_preview_references",
    "materialize_preview_resource",
    "PreviewResourceFile",
    "preview_image",
    "preview_reference",
    "preview_references",
    # Current MCP messaging context.
    "MessagingContext",
    "current_context",
    "set_context",
    "reset_context",
]
