import importlib
import os
from typing import Dict

from loguru import logger

class PrivilegeService:
    def __init__(self):
        pass

    def _get_all_code_privileges(self) -> Dict[str, Dict[str, str]]:
        """
        Scans internal modules (app and core) for 'privileges.py' files,
        imports them, and collects all constant values (uppercase variables).
        """
        privileges_map: Dict[str, Dict[str, str]] = {}
        
        # Import MODULES from modules.py
        try:
            # Assuming modules.py is in the python path (root of back/)
            import modules
            module_list = modules.MODULES
        except ImportError:
            logger.warning("Could not import modules.py. No privileges will be loaded.")
            return privileges_map

        for module_name in module_list:
            # module_name is like 'core.user'
            privileges_module_name = f"{module_name}.privileges"
            
            try:
                priv_module = importlib.import_module(privileges_module_name)
                module_privileges = {}
                for attribute_name in dir(priv_module):
                    # Filter for public uppercase constants
                    if attribute_name.isupper() and not attribute_name.startswith('_'):
                        value = getattr(priv_module, attribute_name)
                        if isinstance(value, str):
                            # Code is the variable name, Value is the description
                            module_privileges[attribute_name] = value
                
                if module_privileges:
                    # Use full module name as key to identify source
                    privileges_map[module_name] = module_privileges
                    
            except ImportError:
                # Module might not have a privileges.py, which is fine
                continue
            except Exception as e:
                logger.error(f"Error loading privileges for {module_name}: {e}")
                continue

        return privileges_map

    def get_code_privileges(self) -> Dict[str, str]:
        """
        Retrieves all privileges defined in the code across all modules (flattened).
        Returns:
            Dict[str, str]: Map of {code: display_name}
        """
        privileges_map = self._get_all_code_privileges()
        all_privileges: Dict[str, str] = {}
        for module_privs in privileges_map.values():
            all_privileges.update(module_privs)
        return all_privileges

    def generate_definitions_files(self, privileges: Dict[str, str]) -> None:
        """
        Generates both:
        - back/core/authorize/definitions.py (Python)
        - front/core/authorize/definitions.ts (TypeScript)
        """
        # 1. Generate Python definitions file
        current_dir = os.path.dirname(os.path.abspath(__file__))
        py_file_path = os.path.join(current_dir, "definitions.py")
        
        py_content = [
            "# Auto-generated by PrivilegeService. Do not edit manually.",
            "",
            "class Privileges:",
            "    \"\"\"",
            "    Accessor for application privileges.",
            "    Constants return the privilege CODE (which matches the constant name).",
            "    \"\"\""
        ]
        
        # Sort for stability
        for code in sorted(privileges.keys()):
            py_content.append(f"    {code} = \"{code}\"")
            
        with open(py_file_path, "w") as f:
            f.write("\n".join(py_content) + "\n")
        logger.info(f"Generated Python privileges definitions at {py_file_path}")
        
        # 2. Generate TypeScript definitions file
        # Write to the mounted volume path (/app-front/core/authorize is mounted to front/core/authorize)
        ts_file_path = "/app-front/core/authorize/definitions.ts"
        
        ts_content = [
            "// Auto-generated by PrivilegeService. Do not edit manually.",
            "",
            "// Privilege constants - use these in navigation definitions",
        ]
        
        # Sort for stability
        sorted_codes = sorted(privileges.keys())
        for code in sorted_codes:
            ts_content.append(f"export const {code} = '{code}'")
        
        ts_content.extend([
            "",
            "/**",
            " * Object grouping all privileges for use in navigation",
            " * Example: privileges: [privileges.PARAMS_ACCESS]",
            " */",
            "export const privileges = {",
        ])
        
        for code in sorted_codes:
            ts_content.append(f"  {code},")
        
        ts_content.extend([
            "} as const",
            "",
        ])
        
        # Ensure directory exists (the volume mount should create it, but just in case)
        ts_dir = os.path.dirname(ts_file_path)
        os.makedirs(ts_dir, exist_ok=True)
        
        with open(ts_file_path, "w") as f:
            f.write("\n".join(ts_content) + "\n")
        logger.info(f"Generated TypeScript privileges definitions at {ts_file_path}")
