"""Read and edit privileges for each Lab surface."""

EVALUATION_ACCESS = "privilege.EVALUATION_ACCESS"
EVALUATION_EDIT = "privilege.EVALUATION_EDIT"

DISPATCHER_EVALUATION_ACCESS = "privilege.DISPATCHER_EVALUATION_ACCESS"
DISPATCHER_EVALUATION_EDIT = "privilege.DISPATCHER_EVALUATION_EDIT"

BRIEFING_EVALUATION_ACCESS = "privilege.BRIEFING_EVALUATION_ACCESS"
BRIEFING_EVALUATION_EDIT = "privilege.BRIEFING_EVALUATION_EDIT"

PLANNER_EVALUATION_ACCESS = "privilege.PLANNER_EVALUATION_ACCESS"
PLANNER_EVALUATION_EDIT = "privilege.PLANNER_EVALUATION_EDIT"

TOPIC_CLASSIFICATION_EVALUATION_ACCESS = "privilege.TOPIC_CLASSIFICATION_EVALUATION_ACCESS"
TOPIC_CLASSIFICATION_EVALUATION_EDIT = "privilege.TOPIC_CLASSIFICATION_EVALUATION_EDIT"

MEMORY_EXTRACTION_EVALUATION_ACCESS = "privilege.MEMORY_EXTRACTION_EVALUATION_ACCESS"
MEMORY_EXTRACTION_EVALUATION_EDIT = "privilege.MEMORY_EXTRACTION_EVALUATION_EDIT"

OUTCOME_REFLECTION_EVALUATION_ACCESS = "privilege.OUTCOME_REFLECTION_EVALUATION_ACCESS"
OUTCOME_REFLECTION_EVALUATION_EDIT = "privilege.OUTCOME_REFLECTION_EVALUATION_EDIT"

GOAL_TRACKING_EVALUATION_ACCESS = "privilege.GOAL_TRACKING_EVALUATION_ACCESS"
GOAL_TRACKING_EVALUATION_EDIT = "privilege.GOAL_TRACKING_EVALUATION_EDIT"

TASK_EXECUTOR_EVALUATION_ACCESS = "privilege.TASK_EXECUTOR_EVALUATION_ACCESS"
TASK_EXECUTOR_EVALUATION_EDIT = "privilege.TASK_EXECUTOR_EVALUATION_EDIT"

CONVERSATION_EXECUTOR_EVALUATION_ACCESS = "privilege.CONVERSATION_EXECUTOR_EVALUATION_ACCESS"
CONVERSATION_EXECUTOR_EVALUATION_EDIT = "privilege.CONVERSATION_EXECUTOR_EVALUATION_EDIT"

VOICE_EXECUTOR_EVALUATION_ACCESS = "privilege.VOICE_EXECUTOR_EVALUATION_ACCESS"
VOICE_EXECUTOR_EVALUATION_EDIT = "privilege.VOICE_EXECUTOR_EVALUATION_EDIT"
