"""Enforce separate line/branch floors per critical domain and inspect changed branches."""

from __future__ import annotations

import argparse
from dataclasses import dataclass
import json
import math
from pathlib import Path
import re
from defusedxml.ElementTree import parse

from pydantic import BaseModel, Field, TypeAdapter


class Domain(BaseModel):
    prefixes: list[str] = Field(min_length=1)
    line_min: float = Field(ge=0, le=100)
    branch_min: float = Field(ge=0, le=100)


@dataclass
class Counts:
    lines: int = 0
    covered: int = 0
    branches: int = 0
    covered_branches: int = 0

    @property
    def line_percent(self) -> float:
        return 100 * self.covered / self.lines if self.lines else 100.0

    @property
    def branch_percent(self) -> float:
        return 100 * self.covered_branches / self.branches if self.branches else 100.0


def measure(xml: Path, domains: dict[str, Domain]) -> tuple[dict[str, Counts], dict[str, set[int]]]:
    counts = {name: Counts() for name in domains}
    missing: dict[str, set[int]] = {}
    root = parse(xml).getroot()
    assert root is not None
    for row in root.findall(".//class"):
        if not row.findall("./lines/line"):
            continue
        filename = row.attrib["filename"].removeprefix("back/")
        owners = [name for name, domain in domains.items() if any(filename.startswith(p) for p in domain.prefixes)]
        if len(owners) != 1:
            raise ValueError(f"Measured source must belong to exactly one domain: {filename}")
        total = counts[owners[0]]
        for line in row.findall("./lines/line"):
            total.lines += 1
            total.covered += int(int(line.attrib["hits"]) > 0)
            if line.get("branch") == "true":
                match = re.search(r"\((\d+)/(\d+)\)", line.attrib["condition-coverage"])
                if match is None:
                    raise ValueError(f"Invalid branch counters: {filename}")
                hit, branches = map(int, match.groups())
                total.covered_branches += hit
                total.branches += branches
                if hit < branches:
                    missing.setdefault(filename, set()).add(int(line.attrib["number"]))
    if any(row.lines == 0 for row in counts.values()):
        raise ValueError("A critical domain is missing from the coverage report")
    return counts, missing


def changed_branches(diff: str, missing: dict[str, set[int]]) -> list[str]:
    filename = ""
    uncovered: list[str] = []
    for line in diff.splitlines():
        if line.startswith("+++ b/back/"):
            filename = line.removeprefix("+++ b/back/")
        elif line.startswith("@@"):
            match = re.search(r"\+(\d+)(?:,(\d+))? @@", line)
            if match:
                start, length = int(match[1]), int(match[2] or 1)
                uncovered.extend(f"back/{filename}:{number}" for number in sorted(missing.get(filename, set()))
                                 if start <= number < start + length)
    return uncovered


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--xml", type=Path, default=Path("/repo/artifacts/coverage.xml"))
    parser.add_argument("--config", type=Path, default=Path(__file__).parents[1] / "coverage-domains.json")
    parser.add_argument("--report", type=Path, default=Path("/repo/artifacts/coverage-domains.json"))
    parser.add_argument("--base", help="Commit against which changed critical branches must be covered")
    parser.add_argument("--diff", type=Path, help="Zero-context Git diff generated by bin/check-coverage.sh")
    parser.add_argument("--record", action="store_true", help="Explicitly record measured floors for review; never used in CI")
    args = parser.parse_args()
    if bool(args.base) != bool(args.diff):
        parser.error("Use make coverage-check to supply both the comparison commit and its diff")
    domains = TypeAdapter(dict[str, Domain]).validate_json(args.config.read_text())
    counts, missing = measure(args.xml, domains)
    failures: list[str] = []
    for name, row in counts.items():
        domain = domains[name]
        if args.record:
            domain.line_min = math.floor(row.line_percent * 100) / 100
            domain.branch_min = math.floor(row.branch_percent * 100) / 100
        elif row.line_percent + 1e-8 < domain.line_min or row.branch_percent + 1e-8 < domain.branch_min:
            failures.append(name)
        print(f"{name}: lines {row.line_percent:.2f}% / {domain.line_min:.2f}%; "
              f"branches {row.branch_percent:.2f}% / {domain.branch_min:.2f}%")
    changed = changed_branches(args.diff.read_text(), missing) if args.diff else []
    report = {"domains": {name: {"lines": row.line_percent, "branches": row.branch_percent,
                               "line_count": row.lines, "branch_count": row.branches} for name, row in counts.items()},
              "below_floor": failures, "uncovered_changed_branches": changed,
              "comparison_base": args.base}
    args.report.parent.mkdir(parents=True, exist_ok=True)
    args.report.write_text(json.dumps(report, indent=2) + "\n")
    if args.record:
        args.config.write_text(json.dumps({name: domain.model_dump() for name, domain in domains.items()}, indent=2) + "\n")
    if failures or changed:
        raise SystemExit("Critical coverage regressed: " + ", ".join([*failures, *changed]))


if __name__ == "__main__":
    main()
