import { test, expect, mount } from './fixtures.mjs'

test('native styles create, change, undo and remove a card containing several paragraphs', async ({ page }, testInfo) => {
  await mount(page, 'core/util/components/RichTextEditor.vue', { props: { modelValue: '<p>First paragraph</p><p><strong>Second paragraph</strong></p>' } })
  const editor = page.locator('.ck-editor__editable')
  // CKEditor keeps a hidden mobile toolbar; the visible style button's label
  // changes to the selected style after applying an encadré.
  const styles = page.locator('.ck-style-dropdown > .ck-button:visible')
  await editor.click()
  await page.keyboard.press('Control+a')
  await styles.click()
  await page.getByRole('option', { name: 'Warning', exact: true }).click()
  const card = editor.locator('blockquote.galaris-callout-warning')
  await expect(card.locator('p')).toHaveCount(2)
  await expect(card.locator('strong')).toHaveText('Second paragraph')
  await styles.click()
  await page.getByRole('option', { name: 'Question', exact: true }).click()
  await expect(editor.locator('.galaris-callout-question')).toBeVisible()
  await expect(editor.locator('.galaris-callout-warning')).toHaveCount(0)
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect(card).toBeVisible()
  const saved = await page.evaluate(() => window.testApp.events.filter(event => event.name === 'update:modelValue').at(-1).value)
  await page.screenshot({ path: testInfo.outputPath('callout-editor.png') })
  await styles.click()
  await page.getByRole('option', { name: 'Warning', exact: true }).click()
  await expect(editor.locator('blockquote')).toHaveCount(0)
  await expect(editor.locator('p')).toHaveCount(2)
  await page.evaluate(content => window.testApp.mount({ component: 'core/util/components/RichText.vue', props: { content }, dark: true }), saved)
  await page.evaluate(() => window.testApp.dark(true))
  await expect(page.locator('.galaris-callout-warning')).toBeVisible()
  await expect(page.locator('.galaris-callout-warning p')).toHaveCount(2)
  await expect(page.locator('.galaris-callout-warning strong')).toHaveText('Second paragraph')
  await page.screenshot({ path: testInfo.outputPath('callout-reader-dark.png') })
})
