import { test, expect, mount } from './fixtures.mjs'

const source = 'const greeting = "Bonjour";\nconsole.log(greeting, 42);'
const content = `<p>Before</p><pre><code class="language-javascript">${source}</code></pre><pre><code class="language-python">print("untouched")</code></pre><p>After</p>`
const saved = page => page.evaluate(() => window.testApp.events.filter(event => event.name === 'update:modelValue').at(-1)?.value)
const toolbar = page => page.getByRole('toolbar', { name: 'Code block options', exact: true })

test('floating controls change the targeted block, keep its text and undo without inserting blocks', async ({ page }, testInfo) => {
  await mount(page, 'core/util/components/RichTextEditor.vue', { props: { profile: 'document', modelValue: content } })
  const blocks = page.locator('.ck-editor__editable pre code')
  await expect(toolbar(page)).toBeHidden()
  await blocks.first().locator('.hljs-keyword').first().click()
  await expect(toolbar(page)).toBeVisible()
  await toolbar(page).getByRole('button', { name: 'Block language', exact: true }).click()
  await page.getByRole('menuitemradio', { name: 'TypeScript', exact: true }).click()
  await expect(blocks).toHaveCount(2)
  await expect(blocks.first()).toHaveClass('language-typescript')
  await expect(blocks.nth(1)).toHaveClass('language-python')
  expect(await blocks.first().innerText()).toBe(source)
  await expect.poll(() => saved(page)).toContain('language-typescript')
  await page.keyboard.press('Control+z')
  await expect(blocks.first()).toHaveClass('language-javascript')
  await toolbar(page).getByRole('button', { name: 'Line numbers', exact: true }).click()
  await expect(blocks.first()).toHaveAttribute('data-code-lines', 'true')
  await expect(blocks.first().locator('.galaris-code-line')).toHaveCount(2)
  expect(await blocks.first().innerText()).toBe(source)
  await toolbar(page).getByRole('button', { name: 'Wrap lines', exact: true }).click()
  await expect(blocks.first()).toHaveAttribute('data-code-nowrap', 'true')
  await expect(blocks.first()).toHaveCSS('white-space', 'pre')
  const html = await saved(page)
  expect(html).toContain('data-code-lines="true"')
  expect(html).not.toMatch(/galaris-code-line|codeLine:|hljs-/)
  await page.screenshot({ path: testInfo.outputPath('floating-code-tools.png') })
  await page.evaluate(() => window.testApp.setProps({ modelValue: '<p>Another document</p>' }))
  await page.evaluate(value => window.testApp.setProps({ modelValue: value }), html)
  await expect(blocks.first()).toHaveAttribute('data-code-lines', 'true')
  await expect(blocks.first()).toHaveAttribute('data-code-nowrap', 'true')
  await expect(blocks.first().locator('.galaris-code-line')).toHaveCount(2)
  await blocks.first().locator('.hljs-keyword').first().click()
  await page.keyboard.press('End')
  await page.keyboard.press('Enter')
  await page.keyboard.insertText('// new line')
  await expect(blocks.first().locator('.galaris-code-line')).toHaveCount(3)
  expect(await saved(page)).not.toMatch(/galaris-code-line|codeLine:/)
  await page.locator('.ck-editor__editable p').last().click()
  await expect(toolbar(page)).toBeHidden()
})

test('copy excludes numbers and copying failures are visible; read-only mode protects authored options', async ({ page }) => {
  await page.addInitScript(() => Object.defineProperty(navigator, 'clipboard', { value: { writeText: async value => { window.copiedCode = value } } }))
  await mount(page, 'core/util/components/RichTextEditor.vue', { props: { profile: 'document', modelValue: content.replace('<code ', '<code data-code-lines="true" ') } })
  const block = page.locator('.ck-editor__editable pre code').first()
  await block.locator('.hljs-keyword').first().click()
  await toolbar(page).getByRole('button', { name: 'Copy code', exact: true }).click()
  expect(await page.evaluate(() => window.copiedCode)).toBe(source)
  await expect(page.getByText('Code copied', { exact: true })).toBeVisible()
  expect(await saved(page)).toBeUndefined()
  await page.evaluate(() => window.testApp.setProps({ readonly: true }))
  await expect(toolbar(page).getByRole('button', { name: 'Block language', exact: true })).toBeDisabled()
  await expect(toolbar(page).getByRole('button', { name: 'Line numbers', exact: true })).toBeDisabled()
  await expect(toolbar(page).getByRole('button', { name: 'Copy code', exact: true })).toBeEnabled()
  await page.evaluate(() => { navigator.clipboard.writeText = async () => { throw new Error('denied') } })
  await toolbar(page).getByRole('button', { name: 'Copy code', exact: true }).click()
  await expect(page.getByText('Unable to copy the code. Please try again.', { exact: true })).toBeVisible()
  await page.evaluate(content => window.testApp.mount({ component: 'core/util/components/RichTextEditor.vue', props: { profile: 'document', modelValue: content, readonly: true } }), content)
  await page.locator('.ck-editor__editable pre code').nth(1).locator('.hljs-built_in').click()
  await expect(toolbar(page)).toBeVisible()
  await expect(toolbar(page).getByRole('button', { name: 'Block language', exact: true })).toBeDisabled()
  await page.evaluate(() => { navigator.clipboard.writeText = async value => { window.copiedCode = value } })
  await toolbar(page).getByRole('button', { name: 'Copy code', exact: true }).click()
  expect(await page.evaluate(() => window.copiedCode)).toBe('print("untouched")')
})

test('line gutters follow wrapped lines in editing, reading and print without entering the text', async ({ page }) => {
  await page.addInitScript(() => { window.print = () => {} })
  await page.setViewportSize({ width: 390, height: 844 })
  const code = '  // ' + 'long text '.repeat(30) + '\nconst value = 42;\n'
  const html = `<pre><code class="language-javascript" data-code-lines="true">${code}</code></pre>`
  await mount(page, 'core/util/components/RichTextEditor.vue', { dark: true, props: { profile: 'document', modelValue: html } })
  const block = page.locator('.ck-editor__editable pre code')
  const numbers = block.locator('.galaris-code-line')
  await expect(block).toHaveAttribute('data-code-lines', 'true')
  await expect(numbers).toHaveCount(3)
  expect((await numbers.nth(1).boundingBox()).y - (await numbers.first().boundingBox()).y).toBeGreaterThan(18)
  await block.locator('.hljs-keyword').click()
  await expect(toolbar(page)).toBeVisible()
  const rect = await toolbar(page).boundingBox()
  expect(rect.x).toBeGreaterThanOrEqual(0)
  expect(rect.x + rect.width).toBeLessThanOrEqual(390)
  await page.keyboard.press('Alt+F10')
  await expect(toolbar(page).getByRole('button', { name: 'Block language', exact: true })).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(toolbar(page)).toBeHidden()
  // Printing belongs to the desktop toolbar; mobile exposes PDF sharing.
  // Preserve the authored code while moving from the wrapped mobile view.
  const editingText = await block.textContent()
  await page.setViewportSize({ width: 1440, height: 900 })
  expect(await block.textContent()).toBe(editingText)
  await page.getByRole('button', { name: 'Print', exact: true }).click()
  const printed = page.frameLocator('.document-print-frame').locator('pre code')
  await expect(printed.locator('.galaris-code-line')).toHaveCount(3)
  expect(await printed.textContent()).toBe(code)
  await page.evaluate(html => window.testApp.mount({ component: 'core/util/components/RichText.vue', props: { profile: 'document', content: html } }), html)
  const reading = page.locator('.rich-content pre code')
  await expect(reading.locator('.galaris-code-line')).toHaveCount(3)
  expect(await reading.textContent()).toBe(code)
})
