/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '///': RouteRecordInfo<
      '///',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '///[...all]': RouteRecordInfo<
      '///[...all]',
      '/:all(.*)',
      { all: ParamValue<true> },
      { all: ParamValue<false> },
      | never
    >,
    '///about': RouteRecordInfo<
      '///about',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '///dashboard': RouteRecordInfo<
      '///dashboard',
      '/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '///license': RouteRecordInfo<
      '///license',
      '/license',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '///welcome': RouteRecordInfo<
      '///welcome',
      '/welcome',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//agent/': RouteRecordInfo<
      '//agent/',
      '/agent',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//authorize/': RouteRecordInfo<
      '//authorize/',
      '/authorize',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//authorize/profile': RouteRecordInfo<
      '//authorize/profile',
      '/authorize/profile',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//browser/settings': RouteRecordInfo<
      '//browser/settings',
      '/browser/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//chat/': RouteRecordInfo<
      '//chat/',
      '/chat',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//connection/mail': RouteRecordInfo<
      '//connection/mail',
      '/connection/mail',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//console/executor': RouteRecordInfo<
      '//console/executor',
      '/console/executor',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//dream/': RouteRecordInfo<
      '//dream/',
      '/dream',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//goal/': RouteRecordInfo<
      '//goal/',
      '/goal',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//harnesses/[id]': RouteRecordInfo<
      '//harnesses/[id]',
      '/harnesses/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '//incident/': RouteRecordInfo<
      '//incident/',
      '/incident',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//lab/': RouteRecordInfo<
      '//lab/',
      '/lab',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//lab/[section]': RouteRecordInfo<
      '//lab/[section]',
      '/lab/:section',
      { section: ParamValue<true> },
      { section: ParamValue<false> },
      | never
    >,
    '//lab/ai-evaluations': RouteRecordInfo<
      '//lab/ai-evaluations',
      '/lab/ai-evaluations',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//llm/': RouteRecordInfo<
      '//llm/',
      '/llm',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//llm/calls': RouteRecordInfo<
      '//llm/calls',
      '/llm/calls',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//memory/': RouteRecordInfo<
      '//memory/',
      '/memory',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//memory/contacts': RouteRecordInfo<
      '//memory/contacts',
      '/memory/contacts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//memory/documents': RouteRecordInfo<
      '//memory/documents',
      '/memory/documents',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//params/': RouteRecordInfo<
      '//params/',
      '/params',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//params/[section]': RouteRecordInfo<
      '//params/[section]',
      '/params/:section',
      { section: ParamValue<true> },
      { section: ParamValue<false> },
      | never
    >,
    '//params/harnesses/[provider]': RouteRecordInfo<
      '//params/harnesses/[provider]',
      '/params/harnesses/:provider',
      { provider: ParamValue<true> },
      { provider: ParamValue<false> },
      | never
    >,
    '//process/': RouteRecordInfo<
      '//process/',
      '/process',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//skill/': RouteRecordInfo<
      '//skill/',
      '/skill',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//task/': RouteRecordInfo<
      '//task/',
      '/task',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//team/': RouteRecordInfo<
      '//team/',
      '/team',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//tools/': RouteRecordInfo<
      '//tools/',
      '/tools',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//topic/': RouteRecordInfo<
      '//topic/',
      '/topic',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//topic/[id]': RouteRecordInfo<
      '//topic/[id]',
      '/topic/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '//user/login': RouteRecordInfo<
      '//user/login',
      '/user/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//user/register': RouteRecordInfo<
      '//user/register',
      '/user/register',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//user/tokens': RouteRecordInfo<
      '//user/tokens',
      '/user/tokens',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//user/users': RouteRecordInfo<
      '//user/users',
      '/user/users',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'app/index/pages/index.vue': {
      routes:
        | '///'
      views:
        | never
      pathParamNames:
        | never
    }
    'app/index/pages/[...all].vue': {
      routes:
        | '///[...all]'
      views:
        | never
      pathParamNames:
        | 'all'
    }
    'app/index/pages/about.vue': {
      routes:
        | '///about'
      views:
        | never
      pathParamNames:
        | never
    }
    'app/index/pages/dashboard.vue': {
      routes:
        | '///dashboard'
      views:
        | never
      pathParamNames:
        | never
    }
    'app/index/pages/license.vue': {
      routes:
        | '///license'
      views:
        | never
      pathParamNames:
        | never
    }
    'app/index/pages/welcome.vue': {
      routes:
        | '///welcome'
      views:
        | never
      pathParamNames:
        | never
    }
    'app/agent/pages/index.vue': {
      routes:
        | '//agent/'
      views:
        | never
      pathParamNames:
        | never
    }
    'core/authorize/pages/index.vue': {
      routes:
        | '//authorize/'
      views:
        | never
      pathParamNames:
        | never
    }
    'core/authorize/pages/profile.vue': {
      routes:
        | '//authorize/profile'
      views:
        | never
      pathParamNames:
        | never
    }
    'app/browser/pages/settings.vue': {
      routes:
        | '//browser/settings'
      views:
        | never
      pathParamNames:
        | never
    }
    'app/chat/pages/index.vue': {
      routes:
        | '//chat/'
      views:
        | never
      pathParamNames:
        | never
    }
    'app/connection/pages/mail.vue': {
      routes:
        | '//connection/mail'
      views:
        | never
      pathParamNames:
        | never
    }
    'app/console/pages/executor.vue': {
      routes:
        | '//console/executor'
      views:
        | never
      pathParamNames:
        | never
    }
    'app/dream/pages/index.vue': {
      routes:
        | '//dream/'
      views:
        | never
      pathParamNames:
        | never
    }
    'app/goal/pages/index.vue': {
      routes:
        | '//goal/'
      views:
        | never
      pathParamNames:
        | never
    }
    'app/harnesses/pages/[id].vue': {
      routes:
        | '//harnesses/[id]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'app/incident/pages/index.vue': {
      routes:
        | '//incident/'
      views:
        | never
      pathParamNames:
        | never
    }
    'app/lab/pages/index.vue': {
      routes:
        | '//lab/'
      views:
        | never
      pathParamNames:
        | never
    }
    'app/lab/pages/[section].vue': {
      routes:
        | '//lab/[section]'
      views:
        | never
      pathParamNames:
        | 'section'
    }
    'app/lab/pages/ai-evaluations.vue': {
      routes:
        | '//lab/ai-evaluations'
      views:
        | never
      pathParamNames:
        | never
    }
    'app/llm/pages/index.vue': {
      routes:
        | '//llm/'
      views:
        | never
      pathParamNames:
        | never
    }
    'app/llm/pages/calls.vue': {
      routes:
        | '//llm/calls'
      views:
        | never
      pathParamNames:
        | never
    }
    'app/memory/pages/index.vue': {
      routes:
        | '//memory/'
      views:
        | never
      pathParamNames:
        | never
    }
    'app/memory/pages/contacts.vue': {
      routes:
        | '//memory/contacts'
      views:
        | never
      pathParamNames:
        | never
    }
    'app/memory/pages/documents.vue': {
      routes:
        | '//memory/documents'
      views:
        | never
      pathParamNames:
        | never
    }
    'core/params/pages/index.vue': {
      routes:
        | '//params/'
      views:
        | never
      pathParamNames:
        | never
    }
    'core/params/pages/[section].vue': {
      routes:
        | '//params/[section]'
      views:
        | never
      pathParamNames:
        | 'section'
    }
    'core/params/pages/harnesses/[provider].vue': {
      routes:
        | '//params/harnesses/[provider]'
      views:
        | never
      pathParamNames:
        | 'provider'
    }
    'app/process/pages/index.vue': {
      routes:
        | '//process/'
      views:
        | never
      pathParamNames:
        | never
    }
    'app/skill/pages/index.vue': {
      routes:
        | '//skill/'
      views:
        | never
      pathParamNames:
        | never
    }
    'app/task/pages/index.vue': {
      routes:
        | '//task/'
      views:
        | never
      pathParamNames:
        | never
    }
    'core/team/pages/index.vue': {
      routes:
        | '//team/'
      views:
        | never
      pathParamNames:
        | never
    }
    'app/tools/pages/index.vue': {
      routes:
        | '//tools/'
      views:
        | never
      pathParamNames:
        | never
    }
    'app/topic/pages/index.vue': {
      routes:
        | '//topic/'
      views:
        | never
      pathParamNames:
        | never
    }
    'app/topic/pages/[id].vue': {
      routes:
        | '//topic/[id]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'core/user/pages/login.vue': {
      routes:
        | '//user/login'
      views:
        | never
      pathParamNames:
        | never
    }
    'core/user/pages/register.vue': {
      routes:
        | '//user/register'
      views:
        | never
      pathParamNames:
        | never
    }
    'core/user/pages/tokens.vue': {
      routes:
        | '//user/tokens'
      views:
        | never
      pathParamNames:
        | never
    }
    'core/user/pages/users.vue': {
      routes:
        | '//user/users'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
