"""Database-backed MCP tool management."""

from .models import Tool as ToolModel, ToolSearchDocument
from .tool_service import get_tool_codes
from .catalog import (
    AgentToolCatalog,
    AgentToolCatalogEntry,
    build_effective_tool_catalog,
    catalog_entry_from_definition,
    catalog_from_entries,
)
from .tool_search_service import (
    ToolIndexRefreshResult,
    ToolSearchHit,
    ToolSearchResult,
    refresh_catalog_index,
    search_catalog,
    search_catalog_in_isolated_session,
)
from .catalog_refresh_service import (
    ToolCatalogRefreshResult,
    refresh_agent_tool_catalog,
    refresh_agents_tool_catalogs,
    refresh_all_tool_catalogs,
    refresh_tool_catalogs,
)
from .schemas import (
    Tool,
    McpAuth,
    McpAuthPublic,
    McpConfig,
    McpConfigPublic,
    FileShareConfig,
    MessengerConfig,
    ListenerConfig,
    ListenerConfigPublic,
    ConnectionParamDef,
    ConnectionSchema,
    ToolGlobalParamPublic,
    ToolGlobalParamUpdate,
    ToolGlobalParamsResponse,
    ToolGlobalParamsUpdate,
    TaskConfig,
    ToolCreate,
    ToolUpdate,
    ToolRead,
    ToolPublic,
    McpToolFunctionPublic,
    ToolMcpCatalogPublic,
    ToolMcpTestRequest,
    ToolMcpTestFunction,
    ToolMcpTestDiagnostic,
    ToolMcpTestResponse,
)
from .agent_registry import (
    AgentToolAdvertisement,
    add_galaris_tools,
    build_agent_tool_advertisement,
    build_agent_galaris_fastmcp,
    build_galaris_fastmcp,
    build_tool_context_instructions,
    build_tool_context_values,
    get_disabled_internal_function_names,
    get_enabled_integrated_tool_codes,
)
from .mandatory_tools import sync_integrated_tool_connections, sync_mandatory_tools
from .admin_access import GALARIS_ADMIN_TOOL_CODE, has_galaris_admin_access, require_galaris_admin_access
from .connection_functions import list_available_connection_functions
from .mcp_loader import (
    McpToolContext,
    McpToolDefinition,
    build_agent_mcp,
    execute_native_mcp_tool,
    list_enabled_native_mcp_definitions,
    list_agent_mcp_tools,
    load_mcp_tools,
    mcp_tool,
    mcp_tools_by_tool_code,
    native_tool_codes_for_connection,
    native_tool_codes_for_tool,
)
from .tool_errors import RecoverableToolError

__all__ = [
    "get_tool_codes",
    "ToolModel",
    "ToolSearchDocument",
    "AgentToolCatalog",
    "AgentToolCatalogEntry",
    "ToolCatalogRefreshResult",
    "ToolIndexRefreshResult",
    "ToolSearchHit",
    "ToolSearchResult",
    "build_effective_tool_catalog",
    "catalog_entry_from_definition",
    "catalog_from_entries",
    "refresh_agent_tool_catalog",
    "refresh_agents_tool_catalogs",
    "refresh_all_tool_catalogs",
    "refresh_catalog_index",
    "refresh_tool_catalogs",
    "search_catalog",
    "search_catalog_in_isolated_session",
    "Tool",
    "McpAuth",
    "McpAuthPublic",
    "McpConfig",
    "McpConfigPublic",
    "FileShareConfig",
    "MessengerConfig",
    "ListenerConfig",
    "ListenerConfigPublic",
    "ConnectionParamDef",
    "ConnectionSchema",
    "ToolGlobalParamPublic",
    "ToolGlobalParamUpdate",
    "ToolGlobalParamsResponse",
    "ToolGlobalParamsUpdate",
    "TaskConfig",
    "ToolCreate",
    "ToolUpdate",
    "ToolRead",
    "ToolPublic",
    "McpToolFunctionPublic",
    "ToolMcpCatalogPublic",
    "ToolMcpTestRequest",
    "ToolMcpTestFunction",
    "ToolMcpTestDiagnostic",
    "ToolMcpTestResponse",
    "McpToolContext",
    "McpToolDefinition",
    "RecoverableToolError",
    "AgentToolAdvertisement",
    "GALARIS_ADMIN_TOOL_CODE",
    "mcp_tool",
    "require_galaris_admin_access",
    "has_galaris_admin_access",
    "list_available_connection_functions",
    "load_mcp_tools",
    "mcp_tools_by_tool_code",
    "native_tool_codes_for_connection",
    "native_tool_codes_for_tool",
    "build_agent_mcp",
    "execute_native_mcp_tool",
    "list_enabled_native_mcp_definitions",
    "list_agent_mcp_tools",
    "add_galaris_tools",
    "build_agent_tool_advertisement",
    "build_agent_galaris_fastmcp",
    "build_galaris_fastmcp",
    "build_tool_context_instructions",
    "build_tool_context_values",
    "get_disabled_internal_function_names",
    "get_enabled_integrated_tool_codes",
    "sync_integrated_tool_connections",
    "sync_mandatory_tools",
]
