"""Detailed shipped Tool descriptions and recognition of previous bridge defaults."""

from collections.abc import Mapping

# Preserve the original short defaults to recognize uncustomized bridge descriptions.
OVERVIEWS: dict[str, str] = {
    "galaris": "Coordinate agents, delegate Tasks, inspect their progress, update your Goals and run assigned business Processes. Resource access remains subject to ownership and sharing rights; administration and conversation controls belong to separate Tools.",
    "conversation": "Turn a conversation into tracked work: create or amend Tasks, inspect their results, pause, resume, retry or stop them, and launch assigned Processes. Resolve pending choices and show documents already accessible to the recipient. These actions are available in conversation context.",
    "memory": "Retain durable facts, decisions and attributed conversation summaries for future work. Inspect and manage sharing of owned memories and documents with humans, agents and teams, or permanently forget an eligible memory. Reading and searching use the File sharing Tool.",
    "file_sharing": "Discover and manipulate authorized resources through canonical URIs: files, documents, memories, attachments and Galaris business records. Read, search, create, edit or transfer content where the provider supports it. This service grants neither access to other agents’ private resources nor an implicit local filesystem.",
    "galaris_admin": "Inspect complete persisted text and voice conversation rounds and LLM calls, including requests, responses, reasoning, tool activity, usage, costs and errors across agents. This optional administrative capability is checked again at each call.",
    "goal_management": "Create, modify, pause, resume, complete and delete long-running Goals for all agents. Enabling this Tool also extends shared Goal commands beyond the caller’s own objectives; concurrent edits remain protected by revisions.",
    "skill_management": "Inspect available skills and read their instructions. Manage authorized skill package files through File sharing at galaris://skill/; system skill packages remain read-only.",
    "process_admin": "Synchronize external workflow definitions and assign Processes to agents. Create, modify and delete definitions, inspect all runs, refresh their state, cancel or retry them and delete terminal runs. Ordinary execution of assigned Processes remains in Galaris.",
    "topic": "Administer the shared thematic organization of Tasks, messages, conversation rounds, memories and documents. Create and edit Topics, inspect their contents, reassign items and merge or split Topics.",
    "search": "Search the public web through the configured local SearXNG service and return results for the agent to assess. Reading full pages and interacting with sites use the Browser Tool.",
    "browser": "Open and navigate web pages in an isolated browser session. Read accessible content, take screenshots, click controls, type, scroll and close the session. Actions on signed-in sites use that session’s access.",
    "chat": "Provide native Galaris text and audio conversations between humans and agents. This messaging connection carries exchanges and attachments; conversation work controls are supplied by the Conversation system Tool.",
    "console": "Execute commands and manage long-running processes on the configured SSH account: start, poll, send input and stop. Its home directory becomes the console:// resource provider for File sharing. Access is limited by that account and the configured host key.",
    "mail": "Search and read IMAP mailboxes, move messages, change flags and trash mail. Send, reply and forward through SMTP with attachments and an AI-agent disclosure signature. Optional human approval and size limits follow the connection settings.",
    "calendar": "Read configured personal or delegated iCalendar feeds, inspect events, check availability and find free slots. Create, update and delete events on writable HTTPS calendars; timezone and working hours follow the connection settings.",
    "n8n": "Connect an external n8n workflow engine to Galaris Processes. Assigned workflows run asynchronously with durable status, inputs, resource references and results. Process execution and administration are exposed through their respective Tools.",
    "image": "Generate and edit images with configured image models, or describe an existing image. Inputs and outputs use authorized resource URIs; availability depends on the configured model capabilities.",
    "audio": "Transcribe an audio or video resource, or retrieve available public YouTube captions. Pass the canonical source URI directly; supported formats, provider availability and configured size limits determine processing.",
    "voice": "Start, list and stop real-time voice calls through an available call provider. Calls require a configured compatible messaging or voice connection and retain their Galaris execution history.",
    "multimedia": "Analyze audio and video and generate sound effects, music or video using configured specialist models. Supply canonical resource URIs; only operations supported by the agent’s configured providers are exposed.",
    "messenger": "Connect an agent to a messaging service to receive and send messages, inspect authorized conversations and exchange attachments. Recipients and rooms remain subject to the connection’s access rules.",
    "matrix": "Receive and send Matrix messages, inspect authorized rooms and exchange attachments through a configured agent account. Homeserver, credentials and supported room capabilities determine access; compatible calls use the Voice Tool.",
    "telegram": "Connect a Telegram bot to receive messages and send replies or attachments. Bot credentials and allowed users and chats govern access; group mention rules determine when the agent responds.",
    "whatsapp": "Connect WhatsApp Cloud messaging to an agent through Meta credentials and webhooks. Exchange supported messages and media with allowed contacts; proactive delivery follows the configured approved template and provider constraints.",
    "one_bot": "Connect a OneBot v11 adapter to Galaris for private and group messages and supported attachments. The adapter’s account, platform and authenticated WebSocket connection determine the available messaging capabilities.",
    "nextcloud_talk": "Use a configured Nextcloud account for Talk conversations and supported attachments. Access follows room membership and server capabilities; compatible real-time calls use the Voice Tool.",
    "nextcloud": "Access the configured Nextcloud account’s files through WebDAV. Browse, read, create, edit and transfer authorized resources using File sharing; account permissions apply to each operation.",
    "grav": "Publish file resources as media on configured Grav pages through the server API. Page and upload settings select the destination; supported file operations are discovered through File sharing.",
    "affine": "Access file blobs in authorized AFFiNE workspaces using the configured account. Transfer resources through File sharing with an explicit workspace destination; this connection does not edit AFFiNE document blocks.",
}

_DETAILS: dict[str, str] = {
    "galaris": "## Capabilities\n\n- **Coordination:** discover agents and inspect their roles to choose whom to delegate to.\n- **Tasks:** launch work for another agent, inspect its state and result, or stop an eligible task.\n- **Goals:** update tracking for owned goals, request another run and ask the referrer within the supported context.\n- **Processes:** discover assigned workflows, inspect inputs, launch them and track or analyze their runs. Also inspect the available tool catalog.\n\n## When to use it\n\nUse this service to distribute work among specialists and retain durable progress. **Example:** delegate research, collect the result, then launch an assigned processing workflow.\n\n## Requirements and limits\n\nMandatory system service. Delegation cannot target the calling agent itself. Task, goal and process access remains controlled; broader administrative operations require their dedicated Tools.",
    "conversation": "## Capabilities\n\n- **Act from a discussion:** submit a background task with a self-contained objective without blocking the exchange.\n- **Track and control:** list recent tasks, inspect progress and results, pause, resume, retry or stop according to their state.\n- **Handle interactions:** submit a user's answer to a pending choice and launch an assigned process.\n- **Present documents:** open a document in internal Chat when the recipient already has read access.\n\n## When to use it\n\nUse it to manage work through natural conversation. **Example:** ask for a report, ask how it is progressing, then pause it. The discussion remains available while work runs.\n\n## Requirements and limits\n\nMandatory system service restricted to conversation context. Document presentation is for internal text Chat; it does not share access or apply to Tasks or external messengers. Commands respect durable states and newer user messages.",
    "memory": "## Capabilities\n\n- **Remember:** retain a fact, preference or decision useful for future work, with an explicit title and content.\n- **Summarize:** condense a conversation into attributed facts, decisions, commitments and open questions instead of retaining the entire transcript.\n- **Share:** inspect recipients and permissions, then share owned memories or documents with a person, agent or team.\n- **Forget:** permanently delete a memory the agent is entitled to forget, including its revisions.\n\n## When to use it\n\nUse it when information should survive a conversation and remain retrievable or shareable. **Example:** retain a project decision and share it with the relevant team. Use a working document for an evolving report.\n\n## Requirements and limits\n\nMandatory system service. Reading, searching and editing documents use File sharing. Sharing requires owner rights; mentioning or linking an item grants no access. Conversation synthesis is limited to 200 messages and 32,000 characters and needs an available model. Acquisition may store, merge or reject a memory.",
    "file_sharing": "## Capabilities\n\n- **Discover:** identify accessible spaces, browse collections and search by name or supported search modes.\n- **Read and inspect:** obtain metadata or read content in bounded portions from its canonical URI.\n- **Write:** create working documents or files, replace content, append text and make targeted edits.\n- **Transfer:** copy across spaces, move or delete where the storage service supports it, and manage document attachments.\n\n## When to use it\n\nUse it as the common entry point to content wherever it is stored. **Example:** read a document, enrich its existing version and copy an attachment to Nextcloud without moving the whole file through the conversation.\n\n## Requirements and limits\n\nMandatory system service. Each space retains its permissions and capabilities: Galaris business records are generally read-only, while documents have immutable HTML or JSON Dataset types and revision checks. Select document_type='dataset' at creation for JSON. External storage requires its own connection; local space exists only with an available Console. Access sharing belongs to Memory.",
    "galaris_admin": "## Capabilities\n\n- **Audit conversations:** inspect the full dataset of a text round or voice turn, including inputs, attempts, results and related objects.\n- **Inspect model calls:** read persisted requests and responses, tool calls, available reasoning, errors and timings.\n- **Review activity:** list LLM-call identifiers within a date range, then open the calls worth examining.\n- **Understand costs:** relate token consumption and recorded costs to execution context.\n\n## When to use it\n\nUse it to diagnose agent behavior, explain a failure or audit an execution. **Example:** start from a failed round, find its model calls and inspect the tool responses.\n\n## Requirements and limits\n\nOptional administrative Tool, inactive by default. It accesses execution data across agents, potentially including sensitive content. Administrative access is checked on every call. It inspects recorded data; it neither replays executions nor modifies results.",
    "goal_management": "## Capabilities\n\n- **Define durable goals:** choose the responsible agent, human referrer, description, cadence and schedule settings.\n- **Manage lifecycle:** update, pause, resume, complete or delete a goal subject to execution constraints.\n- **Administer multiple agents:** extend shared Goal operations beyond the caller's own goals.\n\n## When to use it\n\nUse it to organize recurring or continuing work. **Example:** assign periodic monitoring to an agent, adjust its frequency and pause it when the mission ends.\n\n## Requirements and limits\n\nOptional Tool, inactive by default, with extended rights. Changes use the current revision to prevent concurrent overwrites. Deletion respects active executions; ownership changes are restricted once cycles have started. Ordinary tracking of owned goals remains available through Galaris.",
    "skill_management": "## Capabilities\n\n- **Discover skills:** list an agent's skills, optionally including unavailable entries for an audit.\n- **Read instructions:** open a skill's main file to understand its method and usage rules.\n- **Manage authorized packages:** use File sharing under `galaris://skill/` to create or update instructions and supporting resources in user-managed skills.\n\n## When to use it\n\nUse it to maintain reusable procedures and understand the skills offered to agents. **Example:** inspect a writing procedure, correct its instructions and keep its resources in the same package.\n\n## Requirements and limits\n\nOptional Tool, inactive by default. System skills remain read-only. User skill changes must preserve a valid main file; reading a skill neither executes it nor grants access to all external tools it mentions.",
    "process_admin": "## Capabilities\n\n- **Prepare the catalog:** discover engines, synchronize their workflows and create definitions assigned to agents.\n- **Manage definitions:** inspect, update or delete a process, its descriptive settings and assignment.\n- **Supervise runs:** launch a process for an agent, inspect all runs, refresh state, analyze errors, cancel or retry.\n- **Manage history:** delete a terminal run when removal is requested.\n\n## When to use it\n\nUse it to provide and maintain business automation across the instance. **Example:** discover an n8n workflow, assign it to an agent, then analyze and retry a failed run.\n\n## Requirements and limits\n\nOptional administrative Tool, inactive by default, able to act across agents. Discovery alone does not create an assignment. Terminal-state and retry rules still apply. Galaris is sufficient for agents executing their own assigned processes.",
    "topic": "## Capabilities\n\n- **Build shared organization:** create topics with a title, description and keywords, then update their metadata.\n- **Explore a topic:** inspect its record and list its assigned objects.\n- **Reorganize:** move items between topics, merge topics or split one by selecting the items to transfer.\n\n## When to use it\n\nUse it to keep activities and agents organized consistently. **Example:** group a project's tasks, exchanges and documents, then separate a subproject that has become independent.\n\n## Requirements and limits\n\nOptional administrative Tool. Topics are shared across the instance, so reorganization has a collective scope. Updates check the current revision. Merging or moving changes organization without granting new content access rights.",
    "search": "## Capabilities\n\n- **Find sources:** query the configured SearXNG engine and receive results with titles, links and excerpts.\n- **Explore a subject:** vary search terms to identify relevant documentation, announcements or websites.\n- **Prepare deeper reading:** obtain addresses to open with Browser.\n\n## When to use it\n\nUse it at the start of research or to find a specific public source. **Example:** locate a software product's official documentation, then read the selected page to verify a detail.\n\n## Requirements and limits\n\nOptional service, active by default. SearXNG must be available. Results and excerpts are leads; they guarantee neither accuracy nor freshness. This Tool does not replace reading complete pages or provide access to private website areas.",
    "browser": "## Capabilities\n\n- **Navigate:** open pages, follow addresses, go back and close sessions.\n- **Understand interfaces:** read accessible page content and identify interactive elements.\n- **Act:** click, fill fields, submit input, use the keyboard and scroll.\n- **Inspect appearance:** capture screenshots and change viewport size to examine an interface.\n\n## When to use it\n\nUse it when complete pages must be read or websites require interaction. **Example:** read documentation, fill an authorized form or inspect a page's mobile layout.\n\n## Requirements and limits\n\nOptional Tool, inactive by default. Sessions are isolated and tied to their work; they do not automatically reuse your personal browser. Actions use the account rights in that session. Enabling the Tool does not itself authorize publishing, purchasing or sending data.",
    "chat": "## Capabilities\n\n- **Talk within Galaris:** provide the internal conversation channel between a user and an agent.\n- **Retain exchange context:** associate messages and attachments with their conversation.\n- **Connect discussion to work:** let the conversation controller receive requests and deliver task results.\n\n## When to use it\n\nUse it to work with an agent directly in the Galaris interface without installing an external messenger. **Example:** discuss a project, attach a document and request a result that can be reviewed in Chat.\n\n## Requirements and limits\n\nOptional messaging connection, active by default. Chat carries exchanges; task commands and document presentation come from Conversation. Agent and document access follows Galaris permissions. Available audio features depend on configuration.",
    "console": "## Capabilities\n\n- **Check the environment:** inspect SSH connectivity, permissions, working directory and execution capabilities.\n- **Execute:** run commands or scripts and read output, exit codes and errors.\n- **Track long work:** start a process, poll new output, send input or stop it.\n- **Work with files:** expose the remote home directory to File sharing through `console://`.\n\n## When to use it\n\nUse it for development, calculations, conversions or programmatic file analysis. **Example:** run a script on data, monitor its progress and retrieve the resulting artifact.\n\n## Requirements and limits\n\nRequires a configured SSH server, account and host key; the native console is restricted to the internal harness. Remote account permissions apply. Some process-control commands require the Galaris execution helper. Installed software and network access depend on the server; privileged access is never implicit.",
    "mail": "## Capabilities\n\n- **Read mail:** check connectivity, list folders, search messages and inspect bodies and attachments.\n- **Organize:** change flags, move messages or send them to Trash.\n- **Correspond:** send new mail, reply or forward with authorized attachments.\n- **Control delivery:** use the configured sender identity, an AI-agent disclosure signature and optional human approval.\n\n## When to use it\n\nUse it to process an inbox or maintain correspondence. **Example:** find an exchange, read its attachment and send an approved reply with the deliverable.\n\n## Requirements and limits\n\nRequires IMAP/SMTP settings and account credentials. Deliveries use a retry key to prevent duplicates; sizes and timeouts are bounded. Incoming messages are external content. Enabling Mail does not replace human instructions about recipients and authorized sends.",
    "calendar": "## Capabilities\n\n- **Read:** list configured calendars and inspect events within a period.\n- **Check availability:** detect conflicts for a proposed time and find free slots of a given duration.\n- **Plan:** respect configured timezone, working hours and search increments.\n- **Update calendars:** create, update or delete events on writable calendars.\n\n## When to use it\n\nUse it to prepare appointments and organize time using personal or delegated calendars. **Example:** find a conflict-free one-hour slot and create the event in the intended calendar.\n\n## Requirements and limits\n\niCalendar sources must be configured. Read-only calendars cannot be modified; writes need a compatible HTTPS calendar. Dates and timezones should be explicit. Creating an event does not prove that invitations were sent or accepted by every participant.",
    "n8n": "## Capabilities\n\n- **Connect systems:** use an external n8n engine's workflows as Galaris business processes.\n- **Supply inputs:** pass parameters and file references to assigned workflows.\n- **Track execution:** retain durable status, results and errors even when work finishes later.\n- **Separate roles:** manage definitions with Process administration and run assigned workflows through Galaris or Conversation.\n\n## When to use it\n\nUse it when business operations should chain external integrations in an existing workflow. **Example:** launch document processing or synchronization between services, then collect the result when the process finishes.\n\n## Requirements and limits\n\nRequires a configured n8n engine and workflows that are exposed and assigned. This Tool does not provide an n8n workflow editor within Galaris or automatically create external credentials. Engine permissions and settings remain necessary.",
    "image": "## Capabilities\n\n- **Create:** generate an image from a brief using supported dimensions and destinations.\n- **Edit or compose:** use existing images as references for a change or a new composition.\n- **Understand:** describe an existing image and answer a visual-analysis request.\n- **Reuse analysis:** retain the description in Memory, associated with the document attachment or resource.\n\n## When to use it\n\nUse it to produce illustrations or work with visual information. **Example:** create a report visual, adapt an illustration or describe an image received in a conversation.\n\n## Requirements and limits\n\nOptional Tool requiring compatible models. Inputs must be accessible and destinations writable. Generation can vary and analysis can be imperfect; verify important details. Analysis fails if its description cannot be saved, so it has a durable effect beyond reading.",
    "audio": "## Capabilities\n\n- **Transcribe speech:** process audio files or extract speech from video into text.\n- **Use YouTube:** retrieve available public captions without downloading the entire video.\n- **Handle long content:** retain the transcript and produce a synthesis when processing exceeds the supported threshold.\n- **Choose output:** use supported language and destination options, then reuse the resulting text files.\n\n## When to use it\n\nUse it for interviews, recorded meetings or talks. **Example:** transcribe a recording, read its synthesis and prepare meeting notes in a working document.\n\n## Requirements and limits\n\nOptional Tool. Audio/video files require a configured transcription model; YouTube requires accessible captions. Private, restricted or captionless sources may be rejected. This Tool handles speech; sound, music and video-scene analysis belongs to Multimedia.",
    "voice": "## Capabilities\n\n- **Start calls:** open a real-time voice conversation in a supported room.\n- **Track calls:** list the agent's active sessions to identify those still open.\n- **End calls:** stop an agent-started call using its identifier or room.\n\n## When to use it\n\nUse it when interactive spoken exchange is preferable to a sequence of written messages. **Example:** start a call in a compatible room, discuss a topic with the agent and close the session.\n\n## Requirements and limits\n\nOptional Tool. It depends on a compatible voice or messaging service, its connection and the agent's audio configuration. Calls are real communications, not file transcription or simple speech generation. Available formats, rooms and transports depend on the provider.",
    "multimedia": "## Capabilities\n\n- **Analyze audio:** describe sound events, ambience, instruments or music.\n- **Analyze video:** examine scenes and actions in a video resource.\n- **Create media:** generate sound effects, music or video using options supported by available models.\n- **Track production:** receive a durable process, then inspect progress and the resulting file URIs.\n\n## When to use it\n\nUse it for creative work or analysis beyond speech transcription. **Example:** describe a video sequence, generate ambience or create a short video from a brief.\n\n## Requirements and limits\n\nOptional Tool requiring specialist models; only supported operations are exposed. Generation is asynchronous: a started process is not yet an available media file. Destinations must be writable. Use Audio transcription for spoken words and Image for still images.",
    "messenger": "## Capabilities\n\n- **Receive and reply:** route connected-service messages to the agent and publish its responses.\n- **Recover context:** list accessible rooms and inspect history where the service supports it.\n- **Contact and deliver:** search recipients when supported, send direct messages or deliver attachments.\n- **Retain references:** use incoming media URIs with other Tools without requiring a preliminary local copy.\n\n## When to use it\n\nUse it to make an agent reachable in a communication channel your team already uses. **Example:** receive a question with a file, process it and deliver the result to the intended recipient.\n\n## Requirements and limits\n\nThis describes the shared messaging capability; each bridge declares its own supported functions. A connection and agent identity must be configured. Rooms, recipients and media remain subject to service rules. Delivering an external file and sharing a Galaris document are separate operations.",
    "matrix": "## Capabilities\n\n- **Join exchanges:** receive and send messages using the agent's Matrix account.\n- **Read context:** access authorized rooms and their history within account permissions.\n- **Exchange resources:** receive and deliver supported attachment types, then use file and media Tools to process them.\n- **Configure interaction:** restrict users or rooms, require group mentions and control invitation acceptance according to settings.\n\n## When to use it\n\nUse it to integrate an agent into a team working on Matrix. **Example:** mention the bot in a project room, provide an attachment and receive a response in the same room.\n\n## Requirements and limits\n\nRequires a configured homeserver and Matrix identity. Room membership does not remove connection-specific restrictions. Encryption and calling depend on supported capabilities; automatic invitation acceptance covers authorized unencrypted invitations. Compatible calls use Voice.",
    "telegram": "## Capabilities\n\n- **Talk to a bot:** receive requests and publish agent responses in authorized chats.\n- **Work with media:** exchange supported attachments and media messages, whose URIs can be passed to other Tools.\n- **Set scope:** configure allowed users and chats, plus group mention or direct-reply requirements.\n\n## When to use it\n\nUse it to offer convenient access to an agent through Telegram. **Example:** send a document to the bot, request analysis and receive the response in the same chat.\n\n## Requirements and limits\n\nRequires a created bot and configured token. Capabilities follow the Bot API and the bot's effective permissions, not those of a full user account. Knowing an identifier does not guarantee the bot can contact its owner. Groups and contacts must comply with connection rules.",
    "whatsapp": "## Capabilities\n\n- **Receive requests:** integrate incoming messages delivered by WhatsApp Cloud webhooks.\n- **Reply and deliver:** send supported messages and media using the configured WhatsApp Business identity.\n- **Control contacts:** apply allowed phone numbers and Meta account settings.\n- **Prepare proactive messages:** use an approved template and language when the sending context requires them.\n\n## When to use it\n\nUse it to make an agent reachable through WhatsApp Business. **Example:** receive a request from an allowed contact and return the requested information or document.\n\n## Requirements and limits\n\nRequires Meta configuration, a Business number, credentials and webhooks. Provider conversation and template rules still apply; proactive delivery may need an approved template. This bridge does not automatically connect personal WhatsApp accounts or guarantee support for every media type.",
    "one_bot": "## Capabilities\n\n- **Adapt a platform:** connect a OneBot v11-compatible service to Galaris conversations.\n- **Exchange messages:** receive and send private or group messages supported by the adapter.\n- **Transfer media:** process attachments accepted by the platform and retain references for other Tools.\n\n## When to use it\n\nUse it when your messaging platform provides a OneBot v11 adapter. **Example:** connect an agent account to a community and handle requests in its existing groups.\n\n## Requirements and limits\n\nRequires a working adapter, platform account and a configured WebSocket connection authenticated according to the deployment. Capabilities vary by adapter; the shared protocol does not guarantee every platform feature. This Tool provides messaging, not general administration of the external account.",
    "nextcloud_talk": "## Capabilities\n\n- **Participate in rooms:** receive requests and send responses through the agent's Nextcloud account.\n- **Recover exchanges:** access conversations and history available to that account.\n- **Exchange attachments:** process supported media and their references through File sharing.\n- **Use voice:** call through Voice when supported by the server and provider.\n\n## When to use it\n\nUse it to integrate an agent into collaboration already hosted on Nextcloud. **Example:** discuss a report in a Talk room, provide an attachment and receive the analysis there.\n\n## Requirements and limits\n\nRequires a Nextcloud server and an account authorized in the relevant rooms. Capabilities depend on Talk and server configuration. Talk messaging and general WebDAV file access are separate capabilities; having one does not automatically grant all rights to the other.",
    "nextcloud": "## Capabilities\n\n- **Browse files:** list folders and inspect metadata for resources accessible to the account.\n- **Read and write:** retrieve files, upload new ones and edit supported content.\n- **Organize:** copy, move or delete resources when account permissions allow it.\n- **Transfer across services:** use File sharing to import attachments or export deliverables to Nextcloud.\n\n## When to use it\n\nUse it as an external document space shared with your team's usual tools. **Example:** retrieve a dataset from Nextcloud, process it and upload results to the agreed folder.\n\n## Requirements and limits\n\nRequires server WebDAV access and account credentials. Nextcloud permissions apply to each operation. Commands come from File sharing; this bridge does not provide access to every Nextcloud application or replace a Talk connection.",
    "grav": "## Capabilities\n\n- **Upload media:** send files to a configured Grav page or destination.\n- **Retrieve known files:** read accessible remote resources when their address is known.\n- **Connect creation and publication:** use File sharing to copy an artifact from another space to Grav.\n\n## When to use it\n\nUse it to supply media for a Grav website. **Example:** produce an illustration or PDF and upload it as a resource for an existing page.\n\n## Requirements and limits\n\nRequires a compatible Grav API, authentication and a configured destination. This bridge focuses on media files; it is not a page editor, theme manager or complete website deployment tool. Unsupported listing, move and delete operations are not advertised.",
    "affine": "## Capabilities\n\n- **Upload files:** transfer binary content to an authorized AFFiNE workspace.\n- **Retrieve resources:** download known files using their reference and workspace.\n- **Exchange across storage:** use File sharing to transfer resources between AFFiNE and another accessible space.\n\n## When to use it\n\nUse it when files produced or consumed by an agent belong in an existing AFFiNE workspace. **Example:** upload an image or binary document to the intended workspace and retain the returned reference.\n\n## Requirements and limits\n\nRequires a configured account and an explicit, authorized workspace. The bridge handles binary files, not AFFiNE document blocks, databases or layouts. Uploading a file does not mean it was inserted into a page or shared with new users.",
}

OVERVIEWS["lab"] = "Operate all eleven AI Labs, compare experiments and diagnose Tasks."
_DETAILS["lab"] = (
    "## Capabilities\n\nCreate and clone datasets, capture cases, generate synthetic drafts, "
    "edit experimental prompts, run repeated benchmarks, cancel/resume, rejudge, compare and review results. "
    "Long analyses and generations return durable Process references.\n\n"
    "## Access\n\nDisabled by default. Enable this connection and assign the galaris-lab skill to an "
    "experimenting agent. Real-source capture and Task diagnostics additionally require the "
    "execution-inspection functions of galaris_admin. Agent assessments are attributed separately "
    "from human reviews. Experimental edits do not promote production settings."
)

DESCRIPTIONS: dict[str, str] = {
    code: f"## Purpose\n\n{overview}\n\n{_DETAILS[code]}" for code, overview in OVERVIEWS.items()
}


def bridge_description(
    *configs: Mapping[str, object] | None,
    overview_only: bool = False,
) -> str:
    """Describe configured capabilities, or identify their previous concise default."""
    catalog = OVERVIEWS if overview_only else DESCRIPTIONS
    descriptions: list[str] = []
    for config in configs:
        service = str((config or {}).get("service") or "")
        if service == "internal":
            service = "chat"
        description = catalog.get(service, "")
        if description and description not in descriptions:
            descriptions.append(description)
    return "\n\n".join(descriptions)
