import { test, expect } from '@playwright/test'
import { collectPageErrors } from '../page-errors.mjs'

test('Memory 3D attachment thumbnail persists across document reopening in the assembled app', async ({ page, request }) => {
  const errors = collectPageErrors(page)
  const fixture = await (await request.post('/api/__test/seed?mode=file-catalogue')).json()
  const refresh = page.waitForResponse(response => response.url().endsWith('/api/auth/refresh'))
  await page.goto('/user/login')
  await refresh
  await page.locator('input[type=email]').fill(fixture.email)
  await page.locator('input[type=password]').fill(fixture.password)
  await page.locator('button[type=submit]').click()
  await expect(page.locator('input[type=password]')).toHaveCount(0)
  let downloads = 0
  page.on('request', request => {
    if (new URL(request.url()).pathname === `/api/memory/documents/${fixture.model_document_id}/attachments/${fixture.model_attachment_id}`) downloads++
  })
  const path = `/memory/documents?document_id=${fixture.model_document_id}`
  await page.goto(path)
  const image = page.locator('.model3d-thumbnail img')
  await page.locator('.model3d-thumbnail').scrollIntoViewIfNeeded()
  await expect(image).toBeVisible()
  await expect.poll(() => image.evaluate(element => element.naturalWidth)).toBeGreaterThan(0)
  const first = await image.evaluate(async element => Array.from(new Uint8Array(await (await fetch(element.src)).arrayBuffer())))
  await errors.settle()
  await page.goto('/memory')
  await expect(image).toHaveCount(0)
  await page.goto(path)
  await page.locator('.model3d-thumbnail').scrollIntoViewIfNeeded()
  await expect(image).toBeVisible()
  const second = await image.evaluate(async element => Array.from(new Uint8Array(await (await fetch(element.src)).arrayBuffer())))
  expect(second).toEqual(first)
  expect(downloads).toBe(0)
  await errors.settle()
  expect(errors()).toEqual([])
})

for (const width of [1440, 390]) {
  test(`Memory file locations use real thumbnails, downloads and previews at ${width}px`, async ({ page, request }, testInfo) => {
    await page.setViewportSize({ width, height: 900 })
    const errors = collectPageErrors(page)
    const seeded = await request.post('/api/__test/seed?mode=file-catalogue')
    expect(seeded.ok(), await seeded.text()).toBeTruthy()
    const fixture = await seeded.json()
    const refresh = page.waitForResponse(response => response.url().endsWith('/api/auth/refresh'))
    await page.goto('/user/login')
    await refresh
    await page.locator('input[type=email]').fill(fixture.email)
    await page.locator('input[type=password]').fill(fixture.password)
    const authentication = page.waitForResponse(response => response.url().endsWith('/api/auth/login-json'))
    await page.locator('button[type=submit]').click()
    const session = await (await authentication).json()
    await expect(page.locator('input[type=password]')).toHaveCount(0)
    await errors.settle()
    await page.goto(`/memory?agent=${fixture.agent_id}`)
    if (width < 1024) await page.addLocatorHandler(page.locator('.q-drawer__backdrop'), backdrop => backdrop.click({ position: { x: 380, y: 150 } }), { times: 1 })
    await page.getByText('synthetic.png', { exact: true }).click()
    const detail = page.getByRole('dialog').filter({ has: page.getByLabel('Titre', { exact: true }) })
    for (const uri of fixture.file_uris) await expect(detail.getByText(uri, { exact: true }).last()).toBeVisible()
    const card = detail.locator('.resource-preview-card').filter({ has: page.getByText('synthetic.png', { exact: true }) })
    await card.scrollIntoViewIfNeeded()
    const image = card.getByRole('img', { name: 'synthetic.png', exact: true })
    await expect(image).toBeVisible()
    await expect.poll(() => image.evaluate(element => element.naturalWidth)).toBeGreaterThan(0)
    await card.getByRole('button', { name: 'Ouvrir l’aperçu de synthetic.png', exact: true }).first().click()
    const viewer = page.getByRole('dialog', { name: 'Ouvrir l’aperçu de synthetic.png', exact: true })
    await expect.poll(() => viewer.getByRole('img', { name: 'synthetic.png', exact: true }).evaluate(element => element.naturalWidth)).toBe(160)
    const downloaded = page.waitForEvent('download')
    await viewer.getByRole('button', { name: 'Télécharger synthetic.png', exact: true }).click()
    const chunks = []
    for await (const chunk of await (await downloaded).createReadStream()) chunks.push(chunk)
    const source = await request.get(`/api/file-share/items/${fixture.file_item_id}/resources?agent_id=${fixture.agent_id}`, { headers: { Authorization: `Bearer ${session.access_token}` } })
    const locations = await source.json()
    const memory = await request.get(`/api/memory/items/${fixture.file_item_id}?agent_id=${fixture.agent_id}`, { headers: { Authorization: `Bearer ${session.access_token}` } })
    expect(memory.ok()).toBeTruthy()
    const node = await memory.json()
    expect(node.file_sha256).toMatch(/^[0-9a-f]{64}$/)
    expect(node.urls.sort()).toEqual([...fixture.file_uris].sort())
    expect(locations[0].uri).toBe(node.primary_url)
    expect(node.metadata.resource_uri).toBeUndefined()
    expect(node.metadata.resource_uris).toBeUndefined()
    const bytes = await request.get(`/api/file-share/items/${fixture.file_item_id}/resources/${locations.find(location => location.name === 'synthetic.png').id}/content?agent_id=${fixture.agent_id}&preview=false`, { headers: { Authorization: `Bearer ${session.access_token}` } })
    expect(bytes.ok(), await bytes.text()).toBeTruthy()
    expect(Buffer.concat(chunks)).toEqual(await bytes.body())
    await viewer.getByRole('button', { name: 'Fermer', exact: true }).click()
    await card.screenshot({ path: testInfo.outputPath('catalogue-thumbnail.png') })
    await detail.getByRole('button', { name: 'Fermer', exact: true }).click()
    await expect(detail).toBeHidden()
    await page.getByText('synthetic.png', { exact: true }).click()
    await card.scrollIntoViewIfNeeded()
    await expect(detail.getByRole('img', { name: 'synthetic.png', exact: true })).toBeVisible()
    await detail.getByRole('button', { name: 'Fermer', exact: true }).click()
    const graphResponse = page.waitForResponse('**/api/memory/graph/roots')
    await page.getByRole('tab', { name: 'Graphe', exact: true }).click()
    const graph = await graphResponse
    expect(graph.ok()).toBeTruthy()
    expect((await graph.json()).nodes.map(node => node.id)).toContain(fixture.file_item_id)
    await expect(page.locator('.memory-graph__chart--loading')).toHaveCount(0)
    await expect(page.locator('.memory-graph__chart canvas')).toBeVisible()
    const reloaded = page.waitForResponse('**/api/memory/graph/roots')
    await page.getByRole('button', { name: 'Recharger le graphe', exact: true }).click()
    expect((await (await reloaded).json()).nodes.map(node => node.id)).toContain(fixture.file_item_id)
    await expect(page.locator('.memory-graph__chart--loading')).toHaveCount(0)
    await errors.settle()
    expect(errors()).toEqual([])
  })
}

for (const width of [1440, 390]) {
  test(`Dream tabs and file indexing load real API and reject excluded roots at ${width}px`, async ({ page, request }, testInfo) => {
    await page.setViewportSize({ width, height: 900 })
    const errors = collectPageErrors(page)
    const fixture = await (await request.post('/api/__test/seed')).json()
    const refresh = page.waitForResponse(response => response.url().endsWith('/api/auth/refresh'))
    await errors.settle()
    await page.goto('/user/login')
    await refresh
    await page.locator('input[type=email]').fill(fixture.email)
    await page.locator('input[type=password]').fill(fixture.password)
    const authentication = page.waitForResponse(response => response.url().endsWith('/api/auth/login-json'))
    await page.locator('button[type=submit]').click()
    await authentication
    await expect(page.locator('input[type=password]')).toHaveCount(0)
    await errors.settle()
    await page.goto(`/dream?agent=${fixture.agent_id}`)
    if (width < 1024) await page.addLocatorHandler(page.locator('.q-drawer__backdrop'), backdrop => backdrop.click({ position: { x: 380, y: 150 } }), { times: 1 })
    await expect(page.getByRole('tab', { name: 'Suivi', exact: true })).toHaveAttribute('aria-selected', 'true')
    await expect(page.getByLabel('Racine source (URI)')).toHaveCount(0)
    await expect(page.locator('.dream-history-card')).toHaveCount(0)
    await page.screenshot({ path: testInfo.outputPath('dream-tracking.png'), animations: 'disabled' })
    await page.getByRole('tab', { name: 'Historique', exact: true }).click()
    await expect(page.locator('.dream-history-card')).toBeVisible()
    await page.screenshot({ path: testInfo.outputPath('dream-history.png'), animations: 'disabled' })
    const progress = page.waitForResponse(response => new URL(response.url()).pathname === '/api/file-share/indexing')
    await page.getByRole('tab', { name: 'Indexation', exact: true }).click()
    expect((await progress).status()).toBe(200)
    await expect(page.getByText('Aucun parcours pour cet agent.')).toBeVisible()
    await page.getByLabel('Racine source (URI)').fill('document://')
    const rejection = page.waitForResponse(response => new URL(response.url()).pathname === '/api/file-share/indexing' && response.request().method() === 'POST')
    await page.getByRole('button', { name: 'Indexer maintenant', exact: true }).click()
    expect((await rejection).status()).toBe(403)
    await expect(page.getByText('L’indexation n’a pas pu être chargée ou modifiée.')).toBeVisible()
    await page.getByRole('button', { name: 'Réessayer', exact: true }).click()
    await expect(page.getByText('L’indexation n’a pas pu être chargée ou modifiée.')).toHaveCount(0)
    await page.screenshot({ path: testInfo.outputPath('dream-indexing.png'), animations: 'disabled' })
    await page.getByRole('tab', { name: 'Suivi', exact: true }).click()
    await page.getByRole('tab', { name: 'Indexation', exact: true }).click()
    await expect(page.getByText('Aucun parcours pour cet agent.')).toBeVisible()
    await page.goto(`/memory?agent=${fixture.agent_id}`)
    await expect(page.getByText('Indexation des fichiers', { exact: true })).toHaveCount(0)
    await errors.settle()
    expect(errors()).toEqual([])
  })
}
