import { test, expect } from '@playwright/test'

test('the failure journal opens from navigation and loads occurrences and patterns independently of the Lab', async ({ page, request }) => {
  const fixture = await (await request.post('/api/__test/seed')).json()
  await page.goto('/user/login')
  await page.locator('input[type=email]').fill(fixture.email)
  await page.locator('input[type=password]').fill(fixture.password)
  await page.locator('button[type=submit]').click()
  await expect(page.locator('.user-menu-wrapper').first()).toBeVisible()
  await page.goto('/params')
  const journal = page.getByRole('complementary').getByRole('link', { name: 'Journal des échecs', exact: true })
  await expect(journal).toHaveAttribute('href', '/incident')
  const loaded = page.waitForResponse(response => response.url().includes('/api/incidents?'))
  await journal.click()
  expect((await loaded).status()).toBe(200)
  await expect(page).toHaveURL(/\/incident$/)
  const content = page.locator('.q-page')
  await expect(content.getByRole('heading', { name: 'Journal des échecs', exact: true })).toBeVisible()
  await expect(content.getByRole('tab', { name: 'Occurrences' })).toBeVisible()
  await expect(content.getByRole('tab', { name: 'Motifs regroupés' })).toBeVisible()
  const patterns = page.waitForResponse(response => response.url().includes('/api/incidents/patterns'))
  await content.getByRole('tab', { name: 'Motifs regroupés' }).click()
  expect((await patterns).status()).toBe(200)
  await expect(content).not.toContainText(/Laboratoire|Ajouter un cas au Lab/)
  await page.goto('/lab')
  await expect(page.locator('.lab-home').locator('a[href="/incident"]')).toHaveCount(0)
})
